### PR TITLE
Use aws-sdk-v1 so users can still use this gem when using aws-sdk v2

### PR DESCRIPTION
**Pull request by anark**

### CODE REVIEW

**Comment by toothrot** [comment]
@anark thanks! I'll publish this later today

**Comment by toothrot** [comment]
@anark actually, I no longer have commit access to this repo. Perhaps @dkaufman can help out

**Comment by anark** [comment]
@toothrot @dkaufman Any way to get this merged?

**Comment by dkaufman** [comment]
@anark Sorry for the delay, I've been on vacation for the past couple of weeks. I'm back to work next Wednesday, so will look at it next week.

Cc @toothrot

**Pull request merged**
